#################################
#
# 配置数据源信息
#
#################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源类型  hikariCp
    driver-class-name: com.mysql.jdbc.Driver      # mysql 驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Zxr1234!@#$
    hikari:
      connection-timeout: 30000  # 等待链接池分配的最大时长（毫秒），超过这个时长还没有连接则发生SQLException， 默认：30秒
      minimum-idle: 5            # 最小连接数
      maximum-pool-size: 20      # 最大连接数
      auto-commit: true          # 自动连接
      idle-timeout: 600000       # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
      pool-name: DateSourceHikariCp  #链接池名字
      max-lifetime: 1800000          #链接池生命时长（毫秒），超时而且没有被释放（retired），默认：30分钟 1800000ms
      connection-test-query: SELECT 1


################################
#
# mybatis 配置
#
################################

mybatis:
  type-aliases-package: com.imooc.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml #mappper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

################################
#
# mybatis mapper配置
#
################################
#通用Mapper配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false       #在进行数据库操作的时候，判断表达式 username ！= null 是否追加 false或true
  identity: MYSQL

################################
#
# web 访问端口号  约定8088
#
################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB